CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom        VARCHAR(80)                             NOT NULL,
    prenom     VARCHAR(80)                             NOT NULL,
    email      VARCHAR(160)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(30)                             NOT NULL,
    actif      BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);