ALTER TABLE books
    ADD COLUMN IF NOT EXISTS digital_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE books
    ADD COLUMN IF NOT EXISTS preview_page_count INT NOT NULL DEFAULT 0;

ALTER TABLE books
    ADD COLUMN IF NOT EXISTS pdf_storage_key VARCHAR(500);

CREATE TABLE IF NOT EXISTS physical_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    borrowed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_physical_loans_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_physical_loans_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE INDEX IF NOT EXISTS idx_physical_loans_user_book_status
    ON physical_loans(user_id, book_id, status);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    reserved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_at TIMESTAMP,
    pickup_deadline TIMESTAMP,
    canceled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservations_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_reservations_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE INDEX IF NOT EXISTS idx_reservations_user_book_status
    ON reservations(user_id, book_id, status);

CREATE TABLE IF NOT EXISTS digital_access_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(80) NOT NULL,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uc_digital_access_tokens_token UNIQUE (token),
    CONSTRAINT fk_digital_access_tokens_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_digital_access_tokens_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE INDEX IF NOT EXISTS idx_digital_access_tokens_user_book_status
    ON digital_access_tokens(user_id, book_id, status);
