-- Base catalog_documents + notifications avant V4.
-- V4 historique (checksum prod) fait ALTER TABLE catalog_documents ... :
-- il echoue sur base fraiche si la table n'existe pas.
-- Ce script intercale cree les tables en IF NOT EXISTS :
-- frais -> V3_1 cree, V4 ALTER sur table vide = OK.
-- prod existante -> V3_1 no-op, V4 deja appliquee = skip, checksum intact.
CREATE TABLE IF NOT EXISTS catalog_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content BYTEA NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    uploaded_by VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR(255),
    message VARCHAR(1000) NOT NULL,
    type VARCHAR(255) NOT NULL,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
