create table catalog_documents (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    content_type varchar(120) not null,
    content blob not null,
    uploaded_at timestamp not null,
    uploaded_by varchar(160) not null
);

create table notifications (
    id bigint generated by default as identity primary key,
    recipient_email varchar(160),
    message varchar(500) not null,
    type varchar(60) not null,
    read_at timestamp,
    created_at timestamp not null
);
