CREATE TABLE IF NOT EXISTS catalog_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content BYTEA NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    uploaded_by VARCHAR(255) NOT NULL
);

ALTER TABLE catalog_documents
    ALTER COLUMN content TYPE bytea
    USING NULL::bytea;