CREATE TABLE IF NOT EXISTS catalog_document_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    catalog_document_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    borrowed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_catalog_document_loans_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_catalog_document_loans_document FOREIGN KEY (catalog_document_id) REFERENCES catalog_documents(id)
);

CREATE INDEX IF NOT EXISTS idx_catalog_document_loans_document_status
    ON catalog_document_loans(catalog_document_id, status);

CREATE INDEX IF NOT EXISTS idx_catalog_document_loans_user
    ON catalog_document_loans(user_id, borrowed_at);

CREATE TABLE IF NOT EXISTS catalog_document_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    catalog_document_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    reserved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_at TIMESTAMP,
    pickup_deadline TIMESTAMP,
    canceled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_catalog_document_reservations_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_catalog_document_reservations_document FOREIGN KEY (catalog_document_id) REFERENCES catalog_documents(id)
);

CREATE INDEX IF NOT EXISTS idx_catalog_document_reservations_document_status
    ON catalog_document_reservations(catalog_document_id, status);

CREATE INDEX IF NOT EXISTS idx_catalog_document_reservations_user
    ON catalog_document_reservations(user_id, reserved_at);